name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up JDK
        uses: actions/setup-java@v3  # Updated to the latest version
        with:
          java-version: '11'  # Consider using a more recent version of Java

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_ENV  # Updated to use $GITHUB_ENV

      - name: Clone project
        run: git clone --depth=1 "${{ env.PROJECT }}" project  # Updated to use the environment variable

      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: my-build-apk
          path: ./project/**/**/*.apk  # Ensure the path is accurate
